.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH export 1  "export " 
.SH NAME
export \- Export bookmarks to stdout
.SH SYNOPSIS
\fBexport\fR [\fB\-\-export\-format\fR] [\fB\-\-tag\fR] [\fB\-\-status\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Export bookmarks to stdout
.SH OPTIONS
.TP
\fB\-\-export\-format\fR \fI<EXPORT_FORMAT>\fR [default: json]
Export format (json or csv)
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
json
.IP \(bu 2
csv
.RE
.TP
\fB\-\-tag\fR \fI<TAG>\fR
Filter by tag
.TP
\fB\-\-status\fR \fI<STATUS>\fR
Filter by status
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
