.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH reindex 1  "reindex " 
.SH NAME
reindex \- Rebuild semantic search embeddings for all bookmarks
.SH SYNOPSIS
\fBreindex\fR [\fB\-\-lang\fR] [\fB\-\-collection\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Rebuild semantic search embeddings for all bookmarks
.SH OPTIONS
.TP
\fB\-\-lang\fR \fI<LANG>\fR
Only reindex bookmarks for this language
.TP
\fB\-\-collection\fR \fI<COLLECTION>\fR
Only reindex this collection
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show progress while reindexing
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
