.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH remove 1  "remove " 
.SH NAME
remove \- Remove bookmarks by ID
.SH SYNOPSIS
\fBremove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIIDS\fR> 
.SH DESCRIPTION
Remove bookmarks by ID
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIIDS\fR>
Bookmark IDs to remove (full UUID or unambiguous prefix)
