.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH import 1  "import " 
.SH NAME
import \- Import bookmarks from a JSON file
.SH SYNOPSIS
\fBimport\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Import bookmarks from a JSON file
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
Path to JSON export file
