.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH add-from-snippet 1  "add-from-snippet " 
.SH NAME
add\-from\-snippet \- Create a bookmark by matching a code snippet from stdin against a file
.SH SYNOPSIS
\fBadd\-from\-snippet\fR [\fB\-\-lang\fR] <\fB\-\-file\fR> [\fB\-\-tag\fR] [\fB\-\-note\fR] [\fB\-\-context\fR] [\fB\-\-created\-by\fR] [\fB\-\-dry\-run\fR] [\fB\-\-collection\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Create a bookmark by matching a code snippet from stdin against a file
.SH OPTIONS
.TP
\fB\-\-lang\fR \fI<LANG>\fR
Language identifier; auto\-detected from file extension if omitted
.TP
\fB\-\-file\fR \fI<FILE>\fR
File to search for the snippet in
.TP
\fB\-\-tag\fR \fI<TAG>\fR
Tag label; repeatable
.TP
\fB\-\-note\fR \fI<NOTE>\fR
Semantic annotation
.TP
\fB\-\-context\fR \fI<CONTEXT>\fR
Agent context
.TP
\fB\-\-created\-by\fR \fI<CREATED_BY>\fR [default: user]
Who created this bookmark (defaults to "user")
.TP
\fB\-\-dry\-run\fR
Preview what would be bookmarked without saving
.TP
\fB\-\-collection\fR \fI<COLLECTION>\fR
Add bookmark to this collection (auto\-creates if it doesn\*(Aqt exist)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
