.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH collection 1  "collection " 
.SH NAME
collection \- Manage named groups of bookmarks
.SH SYNOPSIS
\fBcollection\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage named groups of bookmarks
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
collection\-create(1)
Create a new collection
.TP
collection\-delete(1)
Delete a collection (bookmarks are kept)
.TP
collection\-add(1)
Add bookmarks to a collection
.TP
collection\-remove(1)
Remove bookmarks from a collection
.TP
collection\-list(1)
List all collections
.TP
collection\-show(1)
Show bookmarks in a collection
.TP
collection\-resolve(1)
Batch\-resolve all bookmarks in a collection
.TP
collection\-reorder(1)
Reorder bookmarks in a collection
.TP
collection\-help(1)
Print this message or the help of the given subcommand(s)
