.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH reorder 1  "reorder " 
.SH NAME
reorder \- Reorder bookmarks in a collection
.SH SYNOPSIS
\fBreorder\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> <\fIBOOKMARK_IDS\fR> 
.SH DESCRIPTION
Reorder bookmarks in a collection
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Collection name
.TP
<\fIBOOKMARK_IDS\fR>
Bookmark IDs in the desired order
