.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH preview 1  "preview " 
.SH NAME
preview \- Show the current location of a bookmark (file, line, byte range)
.SH SYNOPSIS
\fBpreview\fR [\fB\-\-at\-creation\fR] [\fB\-\-at\-commit\fR] [\fB\-\-resolution\-id\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Show the current location of a bookmark (file, line, byte range)
.SH OPTIONS
.TP
\fB\-\-at\-creation\fR
Preview the file as it was when the bookmark was created
.TP
\fB\-\-at\-commit\fR \fI<AT_COMMIT>\fR
Preview the file at a specific git commit
.TP
\fB\-\-resolution\-id\fR \fI<RESOLUTION_ID>\fR
Use a specific resolution (by ID) instead of the latest
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Bookmark ID (full UUID or unambiguous prefix)
