.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH delete 1  "delete " 
.SH NAME
delete \- Delete a collection (bookmarks are kept)
.SH SYNOPSIS
\fBdelete\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Delete a collection (bookmarks are kept)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Collection name
