.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH gc 1  "gc " 
.SH NAME
gc \- Remove old archived bookmarks
.SH SYNOPSIS
\fBgc\fR [\fB\-\-older\-than\fR] [\fB\-\-dry\-run\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove old archived bookmarks
.SH OPTIONS
.TP
\fB\-\-older\-than\fR \fI<OLDER_THAN>\fR [default: 30d]
Remove archived bookmarks older than this duration (e.g., 30d, 2w, 6m)
.TP
\fB\-\-dry\-run\fR
Show what would be removed without removing
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
