.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH resolve 1  "resolve " 
.SH NAME
resolve \- Batch\-resolve all bookmarks in a collection
.SH SYNOPSIS
\fBresolve\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Batch\-resolve all bookmarks in a collection
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Collection name
