.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH diff 1  "diff " 
.SH NAME
diff \- Show bookmarks affected by recent changes
.SH SYNOPSIS
\fBdiff\fR [\fB\-\-since\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show bookmarks affected by recent changes
.SH OPTIONS
.TP
\fB\-\-since\fR \fI<SINCE>\fR
Show bookmarks affected since this commit
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
