.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH list 1  "list " 
.SH NAME
list \- List bookmarks with optional filters
.SH SYNOPSIS
\fBlist\fR [\fB\-\-tag\fR] [\fB\-\-status\fR] [\fB\-\-file\fR] [\fB\-\-lang\fR] [\fB\-\-author\fR] [\fB\-\-limit\fR] [\fB\-\-collection\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List bookmarks with optional filters
.SH OPTIONS
.TP
\fB\-\-tag\fR \fI<TAG>\fR
Filter by tag
.TP
\fB\-\-status\fR \fI<STATUS>\fR
Filter by status (default: active,drifted)
.TP
\fB\-\-file\fR \fI<FILE>\fR
Filter by file path
.TP
\fB\-\-lang\fR \fI<LANG>\fR
Filter by language (swift, rust, typescript, python)
.TP
\fB\-\-author\fR \fI<AUTHOR>\fR
Filter by author (user, agent, or any identifier)
.TP
\fB\-\-limit\fR \fI<LIMIT>\fR
Maximum results to return
.TP
\fB\-\-collection\fR \fI<COLLECTION>\fR
Filter by collection
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
