#!/usr/bin/env bash
set -euo pipefail

# Render the combined `codemark` Homebrew formula.
#
# dist emits one formula per *package* and can't merge two packages' binaries
# into a single formula, but we want one `brew install .../codemark` to install
# both the CLI (`codemark`, from the codemark-cli archive) and the TUI it shells
# out to (`codemark-tui`, from the codemark-tui archive). So the formula is
# hand-maintained: this script renders it from the PRECOMPILED archives dist
# uploaded to the GitHub release, reading each archive's sha256 from the
# `<asset>.sha256` file dist publishes alongside it (no full downloads needed).
#
# Used by both the local `release.sh` and the `publish-homebrew-formula` job in
# .github/workflows/release.yml so the template lives in exactly one place.
#
# Usage: render-homebrew-formula.sh <version> <output-formula-path>
# Requires: gh, authenticated against the codemark repo.

VERSION=${1:?Version required}
OUTPUT=${2:?Output formula path required}
REPO=${CODEMARK_REPO:-DanielCardonaRojas/codemark}
BASE_URL="https://github.com/${REPO}/releases/download/${VERSION}"

# Read the sha256 of a release asset from its uploaded `<asset>.sha256` file,
# which is formatted as `<sha256> *<filename>` (shasum style).
asset_sha256() {
  local asset="$1"
  # `|| true` so a missing asset yields an empty string (reported by the
  # validation loop below) instead of tripping `set -e`/`pipefail` here.
  { gh release download "${VERSION}" --repo "${REPO}" \
    --pattern "${asset}.sha256" --output - 2>/dev/null | awk '{print $1; exit}'; } || true
}

cli_arm=$(asset_sha256 "codemark-cli-aarch64-apple-darwin.tar.xz")
cli_x86=$(asset_sha256 "codemark-cli-x86_64-apple-darwin.tar.xz")
cli_linux=$(asset_sha256 "codemark-cli-x86_64-unknown-linux-gnu.tar.xz")
tui_arm=$(asset_sha256 "codemark-tui-aarch64-apple-darwin.tar.xz")
tui_x86=$(asset_sha256 "codemark-tui-x86_64-apple-darwin.tar.xz")
tui_linux=$(asset_sha256 "codemark-tui-x86_64-unknown-linux-gnu.tar.xz")

for name in cli_arm cli_x86 cli_linux tui_arm tui_x86 tui_linux; do
  if [ -z "${!name}" ]; then
    echo "error: missing sha256 for '${name}' — are all ${VERSION} archives uploaded to the release?" >&2
    exit 1
  fi
done

cat > "${OUTPUT}" <<EOF
# Generated by scripts/render-homebrew-formula.sh in DanielCardonaRojas/codemark.
# Do not edit by hand; re-run the release flow to regenerate.
#
# Ships precompiled binaries for both \`codemark\` (codemark-cli) and
# \`codemark-tui\` (codemark-tui) so a single install provides the CLI and the
# TUI that \`codemark tui\` shells out to.
class Codemark < Formula
  desc "A structural bookmarking system for code using tree-sitter queries"
  homepage "https://github.com/DanielCardonaRojas/codemark"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE_URL}/codemark-cli-aarch64-apple-darwin.tar.xz"
      sha256 "${cli_arm}"

      resource "codemark-tui" do
        url "${BASE_URL}/codemark-tui-aarch64-apple-darwin.tar.xz"
        sha256 "${tui_arm}"
      end
    end

    on_intel do
      url "${BASE_URL}/codemark-cli-x86_64-apple-darwin.tar.xz"
      sha256 "${cli_x86}"

      resource "codemark-tui" do
        url "${BASE_URL}/codemark-tui-x86_64-apple-darwin.tar.xz"
        sha256 "${tui_x86}"
      end
    end
  end

  on_linux do
    on_intel do
      url "${BASE_URL}/codemark-cli-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "${cli_linux}"

      resource "codemark-tui" do
        url "${BASE_URL}/codemark-tui-x86_64-unknown-linux-gnu.tar.xz"
        sha256 "${tui_linux}"
      end
    end
  end

  def install
    bin.install "codemark"
    resource("codemark-tui").stage do
      bin.install "codemark-tui"
    end
  end

  test do
    assert_match "codemark", shell_output("#{bin}/codemark --version")
    # codemark-tui has no --version flag (an unknown arg just launches the TUI,
    # which needs a TTY). --list-schemes prints headlessly and exits 0, so it's
    # the right smoke test for the bundled binary.
    system bin/"codemark-tui", "--list-schemes"
  end
end
EOF

echo "Wrote ${OUTPUT} (codemark ${VERSION})"
