[metadata]
name = "codemark"
description = "Codemark structural bookmarks"
requirements = ["codemark"]

[source]
command = "cd \"$(dirname $(git rev-parse --path-format=absolute --git-common-dir))\" && codemark list --format tv"
display = "{split:\\t:1}  {split:\\t:4}  {split:\\t:5}"
output = "{split:\\t:0}"

[preview]
command = [
  "cd \"$(dirname $(git rev-parse --path-format=absolute --git-common-dir))\" && codemark preview {split:\\t:0} | jq -r '\"\\(.data.file_path) --highlight-line \\(.data.line_range)\"' | xargs bat --color=always",
  "cd \"$(dirname $(git rev-parse --path-format=absolute --git-common-dir))\" && codemark show {split:\\t:0} --format markdown | glow",
]
offset = "{split:\\t:2}"

[ui.preview_panel]
size = 55

[keybindings]
shortcut = "F5"
ctrl-e = "actions:edit"
ctrl-r = "actions:resolve"
ctrl-d = "actions:details"

[actions.edit]
description = "Open in $EDITOR"
command = "cd \"$(dirname $(git rev-parse --path-format=absolute --git-common-dir))\" && codemark resolve {split:\\t:0} --format '{file}:{line}' | xargs $EDITOR"
mode = "fork"

[actions.resolve]
description = "Re-resolve bookmark"
command = "codemark resolve {split:\\t:0}"
mode = "execute"

[actions.details]
description = "Show full details"
command = "codemark show {split:\\t:0}"
mode = "execute"
